services:
  snowstorm-es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: snowstorm-es03
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - node.name=snowstorm-es03
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm-es01,snowstorm-es02,snowstorm-es03
      - discovery.seed_hosts=snowstorm-es01,snowstorm-es02
      - 'ES_JAVA_OPTS=-Xms4g -Xmx4g'
    volumes:
      - snowstorm-es03-vol:/usr/share/elasticsearch/data
    networks:
      - snowstorm-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://snowstorm-es03:9200']
      interval: 1s
      timeout: 1s
      retries: 60
    mem_limit: 4g
    mem_reservation: 4g

networks:
  snowstorm-network:
    name: snowstorm-network
    external: true

volumes:
  snowstorm-es03-vol:
